### ISSUE TITLE
g_test_trap_fork deprecated

### ISSUE THREAD

**Issue by ghost** [b-k/21st-Century-Examples#4]
In dict_test.c g_test_trap_fork is used to check that "NULL is not a valid key.\n" is sent to stderr if NULL is used as a lookup key for a dict.

g_test_trap_fork is now deprecated in glib2.0 and so this code no longer compiles. It is recommended to use g_test_trap_subprocess instead.

> make dict_test
> cc -g -Wall -O3 `pkg-config --cflags glib-2.0` -I/usr/include/glib-2.0    dict_test.c dict.o keyval.o   -o dict_test
> dict_test.c: In function ‘test_failure’:
> dict_test.c:47:5: warning: ‘g_test_trap_fork’ is deprecated: Use 'g_test_trap_subprocess' instead [-Wdeprecated-declarations]
>      if (g_test_trap_fork(0, G_TEST_TRAP_SILENCE_STDOUT | G_TEST_TRAP_SILENCE_STDERR)){
>      ^
> In file included from /usr/include/glib-2.0/glib.h:82:0,
>                  from dict_test.c:10:
> /usr/include/glib-2.0/glib/gtestutils.h:228:10: note: declared here
>  gboolean g_test_trap_fork               (guint64              usec_timeout,
>           ^
> /tmp/cchuUz21.o: In function `test_failure':
> /home/wkmanire/Projects/21st-century-examples/dict_test.c:47: undefined reference to`g_test_trap_fork'

**Comment by b-k** [comment]
Thanks for pointing this out. Fixed in commit f5eee4a .
